[package]
name = "bevy-web-template"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.19"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = false

[profile.dev]
opt-level = 1
incremental = true

[profile.dev.package."*"]
opt-level = 3

[lints.clippy]
needless_pass_by_value = "allow"